# Generated by Django 3.2.4 on 2021-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='photo',
        ),
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
